### ISSUE TITLE
No caching

### ISSUE THREAD

**Issue by bean5** [baw/atom-hide-files#2]
I hid some files and folders inside a non-hidden folder. Whenever I collapse the parent folder then uncollapse it, though, the tree-view appears to be resetting everything. Is there any way you could cache and re-apply whenever the tree-view does something? I'm new enough that I don't know if there are hooks that you can use.

**Comment by lope** [comment]
Currently there doesn't seem to be an "unhide all children" menu option, so this "bug" seems to be a blessing at the moment.

**Comment by baw** [comment]
Rehiding files/directory has been added in [v0.2.0](https://github.com/baw/atom-hide-files/tree/v0.2.0).

I also added a command to unhide the children of a directory through the parent directory's context menu.
